In [1]:
%run "Helper_Scripts/CWLite_Connect.ipynb"

In [2]:
%run "Helper_Scripts/Setup_Target_Generic.ipynb"

In [3]:
# uncomment based on your target
#%run "Helper_Scripts/Program_XMEGA.ipynb"
%run "Helper_Scripts/Program_STM.ipynb"
#%run "Helper_Scripts/No_Programmer.ipynb"
fw_path = "../../hardware/victims/firmware/simpleserial-aes/simpleserial-aes-cwlitearm.hex"

In [4]:
# program the target
program_target(scope, fw_path)

Detected known STMF32: STM32F302xB(C)/303xB(C)
Extended erase (0x44), this can take ten seconds or more
Attempting to programming 5879 bytes at 0x8000000
STM32F Programming flash...
STM32F Reading flash...
Verified flash OK, 5879 bytes


In [5]:
#Capture Traces
from tqdm import tqdm
from chipwhisperer.capture.acq_patterns.basic import AcqKeyTextPattern_Basic
import numpy as np
import time

ktp = AcqKeyTextPattern_Basic(target=target)

traces = []
textin = []
keys = []
N = 2000  # Number of traces
target.init()
for i in tqdm(range(N), desc='Capturing traces'):
    # run aux stuff that should come before trace here

    key, text = ktp.newPair()  # manual creation of a key, text pair can be substituted here
    textin.append(text)
    keys.append(key)

    #target.reinit()

    target.setModeEncrypt()  # only does something for targets that support it
    target.loadEncryptionKey(key)
    target.loadInput(text)

    # run aux stuff that should run before the scope arms here

    scope.arm()

    # run aux stuff that should run after the scope arms here

    target.go()
    timeout = 50
    # wait for target to finish
    while target.isDone() is False and timeout:
        timeout -= 1
        time.sleep(0.01)

    try:
        ret = scope.capture()
        if ret:
            print('Timeout happened during acquisition')
    except IOError as e:
        print('IOError: %s' % str(e))

    # run aux stuff that should happen after trace here
    _ = target.readOutput()  # clears the response from the serial port
    traces.append(scope.getLastTrace())

#Convert traces to numpy arrays
trace_array = np.asarray(traces)  # if you prefer to work with numpy array for number crunching
textin_array = np.asarray(textin)
known_keys = np.asarray(keys)  # for fixed key, these keys are all the same

Capturing traces: 100%|██████████| 2000/2000 [05:08<00:00,  6.55it/s]


In [6]:
from lascar import *
from lascar.tools.aes import sbox

def generate_selection_function(byte):
    def selection_with_guess(value, guess): # selection_with_guess function must take 2 arguments: value and guess
        #print("value: {}".format(value))
        return hamming(sbox[value[byte] ^ guess])
    return selection_with_guess

In [7]:
mycontainer =  TraceBatchContainer(trace_array, textin_array)

In [8]:
guess_range = range(256)

In [9]:
cpa_engines = [CpaEngine("cpa_%02d" % i, generate_selection_function(i), guess_range) for i in range(16)]

In [30]:
from lascar.output.parse_results import apply_parse
import pandas as pd
from IPython.display import clear_output
class JupyterOutputMethod(OutputMethod):
    def _update(self, engine, results):
        engine.output_parser_mode = "argmax"
        results_parsed = apply_parse(engine, abs(results))
        if results_parsed is None:
            return
        df = pd.DataFrame(results_parsed).sort_values(2, axis=0)
        fd = df.transpose()
        def formatter(stats):
            return str("{}".format(stats))
        clear_output(wait=True)
        display(fd.head().style.format(formatter))
        
session = Session(mycontainer, engines=cpa_engines, output_method=JupyterOutputMethod(*cpa_engines), output_steps=500).run(batch_size=100)

Session |100%||2000 trc/2000 | (18 engines, batch_size=100, leakage_shape=(5000,)) |Time:  0:00:20


AttributeError: 'JupyterOutputMethod' object has no attribute '_finalize'

In [69]:
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
output_notebook()
p = figure()
for i in range(16):
    results = cpa_engines[i].finalize()
    xrange = range(len(results[0x2B]))
    guess = abs(results).max(1).argmax()
    print("Best Guess is {:02X} (Corr = {})".format(guess, abs(results).max()))
    p.line(xrange, results[guess])
    
show(p)

Loading BokehJS ...

Best Guess is 2B (Corr = 0.8819549855894722)
Best Guess is 7E (Corr = 0.8641673643569957)
Best Guess is 15 (Corr = 0.8861143398259638)
Best Guess is 16 (Corr = 0.8881167317269975)
Best Guess is 28 (Corr = 0.8867853178287347)
Best Guess is AE (Corr = 0.8788261857956764)
Best Guess is D2 (Corr = 0.8726894924236483)
Best Guess is A6 (Corr = 0.8686279256542734)
Best Guess is AB (Corr = 0.8988567019274656)
Best Guess is F7 (Corr = 0.8841709148770263)
Best Guess is 15 (Corr = 0.8842457852361437)
Best Guess is 88 (Corr = 0.876149844333077)
Best Guess is 09 (Corr = 0.8935485562108787)
Best Guess is CF (Corr = 0.8658320176664109)
Best Guess is 4F (Corr = 0.8790855835734749)
Best Guess is 3C (Corr = 0.8747517031930832)


In [47]:
print(results)

[[-0.09475346 -0.05683607 -0.07875837 ... -0.09013332 -0.05793832
  -0.10748509]
 [-0.02612699  0.04846655  0.04347683 ...  0.185771    0.16331949
   0.15497122]
 [-0.01171707 -0.07218269 -0.00485762 ... -0.00583763  0.00855455
  -0.01280755]
 ...
 [-0.02969102  0.00199233 -0.02801654 ...  0.1284462   0.12930057
   0.12500131]
 [ 0.04364144  0.09195242  0.0383671  ...  0.00721142  0.01861461
   0.        ]
 [ 0.04094363 -0.06576713  0.03622526 ... -0.1391642  -0.14273133
  -0.10194352]]


In [68]:
from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()
xrange = range(len(results[0x2B]))
print(xrange)
print(len(results))
p = figure()
#p.line(xrange, traces[5],line_color='red')
p.line(xrange, results[0x3C])
show(p)

Loading BokehJS ...

range(0, 5000)
256


In [94]:
print(mycontainer.values)

[[219  98  78 ... 162 199  74]
 [228 136 198 ...  24 155  71]
 [111  52  64 ... 148  49 139]
 ...
 [244 166 212 ... 207 249 141]
 [ 77 175 127 ...  42 195  42]
 [101 146 191 ... 163 217  79]]
